version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/backend/cesi_zen_api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/CesiZenMobile"
    schedule:
      interval: "weekly"
