services:
  # --- Service API Django ---
  backend:
    build: 
      context: ./backend/cesi_zen_api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/cesi_zen_api:/app
      - /app/.venv
    environment:
      - PYTHONUNBUFFERED=1

  # --- Service Application Mobile Web ---
  frontend:
    build: 
      context: ./CesiZenMobile
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    volumes:
      - ./CesiZenMobile:/app
      - /app/node_modules
    depends_on:
      - backend