services:
  # --- Service Database Postgres ---
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=cesi_zen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cesi_zen_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cesi_zen"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Service API Django ---
  backend:
    build: 
      context: ./backend/cesi_zen_api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend/cesi_zen_api:/app
      - /app/.venv
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=cesi_zen
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=cesi_zen_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - USE_POSTGRES=True
      - SECRET_KEY=django-insecure-5a8j@)kwz!nsb^-5+7pp45$gk)vr-(h*_j56ao#!&ui&8rd^7k
      - DEBUG=True
    depends_on:
      db:
        condition: service_healthy

  # --- Service Application Mobile Web ---
  frontend:
    build: 
      context: ./CesiZenMobile
      dockerfile: Dockerfile.dev
    ports:
      - "8100:8100"
    volumes:
      - ./CesiZenMobile:/app
      - /app/node_modules
    depends_on:
      - backend

  # --- Service Prometheus (Stockage des métriques) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: cesizen-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  # --- Service Grafana (Visualisation des métriques) ---
  grafana:
    image: grafana/grafana:latest
    container_name: cesizen-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

volumes:
  postgres_data: