# Generated by Django 6.0.1 on 2026-03-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breathingexercice",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
