# Generated by Django 6.0.1 on 2026-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_breathingexercice_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
