# Generated by Django 6.0.1 on 2026-03-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingexercice',
            name='loop',
        ),
    ]
