services:
  # --- Service Database Postgres ---
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Service API Django ---
  backend:
    image: ghcr.io/lougitta/cezizen/backend:latest
    ports:
      - "8000:8000"
    volumes:
      - django_static:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USE_POSTGRES=True
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ENVIRONMENT=${ENVIRONMENT}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # --- Service Application Mobile Web ---
  frontend:
    image: ghcr.io/lougitta/cezizen/frontend:latest
    ports:
      - "80:80"
    volumes:
      - django_static:/usr/share/nginx/html/static
    depends_on:
      - backend
    restart: unless-stopped

  # --- Service de collecte de métriques des conteneurs ---
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cesizen-cadvisor
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  # --- Service Prometheus (Stockage des métriques) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: cesizen-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - cadvisor
    restart: unless-stopped

  # --- Service Grafana (Visualisation des métriques) ---
  grafana:
    image: grafana/grafana:latest
    container_name: cesizen-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    restart: unless-stopped

volumes:
  django_static:
  postgres_data: