name: "[CD] PROD"

on:
  push:
    branches: ["main"]

jobs:
  simulate-deploy-prod:
    name: Simulation Déploiement PROD
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message de test
        run: |
          echo "======================================================"
          echo "✅ Le déclencheur PROD fonctionne parfaitement !"
          echo "🔜 Prochaine étape : configurer le vrai déploiement."
          echo "======================================================"
