name: "[CD] PROD"

on:
  push:
    branches: ["main"]

jobs:
  simulate-deploy-prod:
    name: Notification CD PROD
    runs-on: ubuntu-latest

    steps:
      - name: Afficher le statut de déploiement
        run: |
          echo "======================================================"
          echo "📢 Branche main mise à jour."
          echo "🚀 La VM de production va détecter et pull les modifications."
          echo "======================================================"
